# Generated by Django 5.2.6 on 2025-10-02 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncentiveDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.CharField(max_length=200)),
                ('month', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('day', models.CharField(max_length=10)),
                ('target', models.IntegerField(default=0)),
                ('achieved', models.IntegerField(default=0)),
                ('returns', models.IntegerField(default=0)),
                ('incentive_percent', models.FloatField(default=0)),
                ('salesman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.salesman')),
            ],
        ),
    ]
