# Generated by Django 5.2.6 on 2025-10-04 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_incentivedetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incentivedetail',
            name='day',
        ),
    ]
