# Generated by Django 5.2.6 on 2025-10-04 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_incentivedetail_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='incentivedetail',
            name='week',
            field=models.IntegerField(default=1),
        ),
    ]
