# Generated by Django 5.2.6 on 2025-10-04 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_incentivedetail_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incentivedetail',
            name='week',
            field=models.CharField(max_length=1),
        ),
    ]
